---
title: "Paquetes en R"
author:
  - name: "Mtro. Santiago Ríos"
    email: santiagoboo99@gmail.com
    affiliation: 
      - name: Cursos Orca
        city: CDMX
        url: orcaasesina.com
format: 
    live-revealjs: 
        theme: serif
        toc: true
        scrollable: true
        progress: true
        slide-number: true
        incremental: true
        lang: es
        logo: "https://tidyverse.tidyverse.org/logo.png"
# webr:
#     packages: 
#         - dplyr
engine: knitr
---

{{< include ../_extensions/r-wasm/live/_knitr.qmd >}}

## Introducción
- Una de las características más poderosas de R es la capacidad de ampliar su funcionalidad mediante *paquetes*. 
- Un paquete en R es una colección de funciones, datos y documentación que extienden las herramientas básicas del lenguaje. 
- Existen miles de paquetes disponibles que facilitan tareas como análisis estadístico, visualización de datos, manipulación de datos, y más.
- Por ejemplo, el paquete `ggplot2` permite realizar gráficos avanzados, mientras que `dplyr` su usa para manipulación de datos.

## Cómo Instalar Paquetes en R

- Puedes instalar un paquete desde [CRAN](https://cran.r-project.org/) (la red de archivos principal de R) usando la función `install.packages()`.
- La sintaxis para instalar un paquete es la siguiente:

```r
# Instalar un paquete
install.packages("nombre_del_paquete")`
```

## Ejemplo
- Vamos a instalar el conjunto de paquetes 'tidyverse', que incluye muchos paquetes útiles para el análisis de datos.
- Veremos más sobre estos paquetes en las próximas lecciones, por ahora solo necesitas instalarlos.
- Para instalar 'tidyverse', usa: `install.packages("tidyverse")`

##

realiza la instalación en la consola que se encuentra abajo. Después, instalalo de la misma manera en tu RStudio. Espera unos segundos hasta que tengas un mensaje de la consola. Por el momento verás algunas advertencias, pero no te preocupes por ellas.

```{webr}
install.packages("tidyverse") 

```

## Cargar Paquetes en R

- Comprueba que el paquete 'tidyverse' se haya instalado correctamente en tu RStudio.
- Para esto, carga el paquete con la función `library(nombre_del_paquete)`.
- Si todo está bien, no deberías ver ningún mensaje de error. Deberías ver un mensaje similar a `Attaching core tidyverse packages...` 
- Corre el siguiente código en esta consola y en tu RStudio.

```{webr}
library(tidyverse)

```
---

##
- Solamente se necesita instalar el paquete una vez en tu sesión de R.
- Sin embargo, necesitas cargarlo en cada sesión de R en la que quieras usarlo.
- Cuando cargas un paquete, estamos haciendo disponible a R todas las funciones y datos que contiene.


## Breve nota sobre Tidyverse
- El Tidiverse contiene varios paquetes que son útiles para el análisis de datos.
- Algunos de los paquetes más útiles son:
    - `ggplot2` - para gráficos
    - `dplyr` - para manipulación de datos
    - `tidyr` - para limpieza de datos
- Puedes ver todos los paquetes que contiene Tidyverse con la función `tidyverse_packages()`.
- Puedes acceder a un paquete del tidyverse cargando todos los paquetes con `library(tidyverse)` o cargando un paquete específico con `library(dplyr)`.
- Los paquetes dentro del Tidyverse siguen una estructura similar, por lo que es fácil aprender a usarlos. Esto se verá más adelante en el curso.


# Fin