---
title: "Visualizar diferencia de medias"
author:
  - name: "Mtro. Santiago Ríos"
    email: santiagoboo99@gmail.com
    affiliation: 
      - name: Cursos Orca
        city: CDMX
        url: orcaasesina.com
format: 
    live-html:
        highlightStyle: github
        highlightLines: true
        theme: minty
toc: true
sidebar: false
webr:
    packages: 
        - dplyr
        - patchwork
    render-df: gt-interactive
engine: knitr
---


## Visualizar diferencia de medias

- Antes de continuar los siguientes temas, vamos a ver cómo visualizar la diferencia de medias entre dos grupos en R. 



Un problema con los gráficos de barras de error en diseños de medidas repetidas

- Vimos que es importante visualizar las diferencias entre grupos usando barras de error.
- Ahora vamos a examinar un problema que ocurre cuando graficamos barras de error en diseños de medidas repetidas. Para hacerlo, utilizaremos un ejemplo que uso a lo largo de este capítulo (no porque sea demasiado perezoso para idear diferentes conjuntos de datos, sino porque este ejemplo me permite ilustrar varias cosas). El ejemplo se refiere a si la aracnofobia (miedo a las arañas) es específica para arañas reales o si las imágenes de arañas pueden evocar niveles similares de ansiedad. Se usaron veinticuatro personas con aracnofobia. A doce se les pidió que jugaran con una gran tarántula peluda con grandes colmillos y una mirada malvada en sus ocho ojos. Se midió su ansiedad posterior. A los otros doce solo se les mostraron imágenes de la misma gran tarántula peluda y se midió su ansiedad nuevamente. Los datos se encuentran en la Tabla 9.1 (y en spiderLong.dat si tienes dificultad para ingresarlos en R por ti mismo). Recuerda que cada fila de los datos representa los datos de un participante diferente. Por lo tanto, necesitas una columna que represente el grupo al que pertenecían y una segunda columna que represente su ansiedad.

Ahora, imaginemos que hubiéramos recopilado estos datos utilizando los mismos participantes; es decir, todos los participantes tenían su ansiedad evaluada después de ver la araña real, pero también después de ver la imagen (obviamente en un orden contrabalanceado). Los datos ahora estarían organizados de manera diferente en R. En lugar de tener una variable de codificación y una sola columna con puntuaciones de ansiedad, organizaríamos los datos en dos columnas (una representando la condición de la imagen y otra la condición real). Los datos se muestran en la Tabla 9.2 (y en spiderWide.dat si tienes dificultad para ingresarlos en R por ti mismo). Aunque las puntuaciones de ansiedad son idénticas a las de los datos entre grupos (Tabla 9.1), estamos pretendiendo que provinieron de las mismas personas en lugar de diferentes personas.

La Figura 9.2 muestra los gráficos de barras de error de los dos diseños diferentes. Recuerda que los datos son exactamente los mismos, todo lo que ha cambiado es si el diseño usó a los mismos participantes (medidas repetidas) o diferentes (independientes). Descubrimos en el Capítulo 1 que los diseños de medidas repetidas eliminan algunas variables extrañas (como la edad, CI, etc.) y por lo tanto pueden darnos más sensibilidad en los datos. Por eso, esperaríamos que nuestros gráficos fueran diferentes: el gráfico de medidas repetidas debería reflejar la mayor sensibilidad en el diseño. Observando los dos gráficos de barras de error, ¿puedes notar esta diferencia entre los gráficos?

Yo tampoco puedo; y este es el problema. Los gráficos no deberían ser iguales. La lección es: No uses gráficos de barras de error cuando tienes grupos de medidas repetidas. O si lo haces, ajusta los datos antes de graficar (Loftus & Masson, 1994).

Figura

FIGURA 9.2 Dos gráficos de barras de error de los datos de ansiedad en presencia de una araña real o una fotografía. Los datos a la izquierda se tratan como si fueran de diferentes participantes, mientras que los de la derecha se tratan como si fueran del mismo participante.

Paso 1: calcular la media para cada participante

Para corregir las barras de error en medidas repetidas se requieren varios pasos, pero ninguno es particularmente difícil. Para comenzar, necesitamos calcular la ansiedad promedio para cada participante. Estamos usando el dataframe spiderWide, por lo que las puntuaciones de los participantes se almacenan en dos columnas, por lo que simplemente necesitamos sumar estas columnas y dividir por 2 ejecutando:

spiderWide$pMean <- (spiderWide$picture + spiderWide$real) / 2

 

Este comando crea una variable llamada pMean en el dataframe spiderWide, sumando las puntuaciones de picture y real (del mismo dataframe) y dividiendo por 2.

Paso 2: calcular la media general

La media general es la media de todas las puntuaciones (sin importar de qué condición provienen) y, por lo tanto, para los datos actuales, este valor será la media de las 24 puntuaciones. Una forma bastante simple de calcular este valor es usar la función c(), con la que estamos familiarizados, para combinar las variables picture y real en una sola variable, y luego aplicar la función mean() a esta nueva variable. Podemos hacer esto con un solo comando:

grandMean <- mean(c(spiderWide$picture, spiderWide$real))

 

Ejecutar este comando crea una variable llamada grandMean, que es la media de picture y real combinadas en una sola variable (c(spiderWide$picture, spiderWide$real)); en otras palabras, es la media de todas las puntuaciones.

Paso 3: calcular el factor de ajuste

Si observas la variable llamada pMean, notarás que los valores para cada participante son diferentes, lo que nos indica que algunas personas tenían mayor ansiedad que otras en todas las condiciones. El hecho de que las puntuaciones medias de ansiedad de los participantes difieran representa diferencias individuales entre diferentes personas (así que representa el hecho de que algunos participantes generalmente tienen más miedo a las arañas que otros). Estas diferencias en la ansiedad natural contaminan los gráficos de barras de error, razón por la cual si no ajustamos los valores que graficamos, obtendremos el mismo gráfico como si se hubiera usado un diseño independiente. Loftus y Masson (1994) argumentan que para eliminar esta contaminación deberíamos igualar las medias entre participantes (es decir, ajustar las puntuaciones en cada condición de manera que cuando tomamos la puntuación media entre condiciones, sea igual para todos los participantes). Para hacerlo, necesitamos calcular un factor de ajuste restando la puntuación media de cada participante (pMean) de la media general (grandMean):

spiderWide$adj <- grandMean - spiderWide$pMean

 

Ejecutar este comando crea una variable adj (abreviatura de ajuste) en el dataframe spiderWide tomando la variable grandMean (que acabamos de calcular) y restando de ella la ansiedad media para cada participante (que se almacena en la variable pMean, que calculamos anteriormente).

Hay una nueva variable en el editor de datos llamada adj. Las puntuaciones en esta columna representan la diferencia entre la ansiedad media de cada participante y el nivel de ansiedad media de todos los participantes. Notarás que algunos de los valores son positivos, y estos participantes son los que estaban menos ansiosos que el promedio. Otros participantes estaban más ansiosos que el promedio, y tienen puntuaciones negativas de ajuste. Ahora podemos usar estos valores de ajuste para eliminar las diferencias entre sujetos en ansiedad.

Paso 4: crear valores ajustados para cada variable

Hasta ahora, hemos calculado la diferencia entre la puntuación media de cada participante y la puntuación media de todos los participantes (la media general). Esta diferencia puede usarse para ajustar las puntuaciones existentes de cada participante. Primero necesitamos ajustar las puntuaciones en la condición de la imagen. Todo lo que hacemos es tomar la puntuación original (picture) y añadir a ella el valor del ajuste (adj):

spiderWide$picture_adj <- spiderWide$picture + spiderWide$adj

 

Ejecutar este comando crea una variable picture_adj en el dataframe spiderWide sumando el ajuste (spiderWide$adj) a las puntuaciones de ansiedad original tras ver la imagen (spiderWide$picture). Podemos hacer exactamente lo mismo para crear valores ajustados de real:

spiderWide$real_adj <- spiderWide$real + spiderWide$adj

 

Ejecutar este comando crea una variable real_adj en el dataframe spiderWide sumando el ajuste (spiderWide$adj) a las puntuaciones de ansiedad original tras ver la araña real (spiderWide$real). El dataframe ahora se ve así:

Figura

Ahora, las variables real_adj y picture_adj representan la ansiedad experimentada en cada condición, ajustada de manera que se eliminan todas las diferencias entre sujetos. Si no me crees, puedes usar la función mean() para crear una variable pMean2 que sea el promedio de real_adj y picture_adj (tal como lo hicimos en la sección 9.3.2). Deberías encontrar que el valor en esta columna es el mismo para cada participante, demostrando así que la variabilidad entre sujetos en las medias ha desaparecido: el valor será 43.50 - la media general. También podemos unir todos estos pasos en una función para usar con otros dataframes (Consejo del Alma de R 9.1).

Figura

AUTOEVALUACIÓN

Figura Crear un gráfico de barras de error de la media de los valores ajustados que acabas de hacer (real_adj y picture_adj).

Figura

Figura

FIGURA 9.3 Gráfico de barras de error de los valores ajustados del dataframe spiderWide

El gráfico de barras de error resultante se muestra en la Figura 9.3. Compara este gráfico con los gráficos en la Figura 9.2 - ¿qué diferencias ves? La primera cosa que se nota es que las medias en las dos condiciones no han cambiado. Sin embargo, las barras de error han cambiado: se han hecho más pequeñas. Además, mientras que en la Figura 9.2 las barras de error se superponen, en este nuevo gráfico no se superponen. En el Capítulo 2 descubrimos que cuando las barras de error no se superponen podemos estar bastante seguros de que nuestras muestras no proceden de la misma población (y por lo tanto nuestra manipulación experimental ha sido exitosa). Por lo tanto, cuando graficamos las barras de error adecuadas para los datos de medidas repetidas, muestra la sensibilidad extra que tiene este diseño: las diferencias entre condiciones parecen ser significativas, mientras que cuando se usan diferentes participantes, no parece haber una diferencia significativa. (Recuerda que las medias en ambas situaciones son idénticas, pero el error de muestreo es menor en el diseño de medidas repetidas). Ampliaré este punto en la sección 9.7.