---
title: "ANOVA Mixto"
author:
  - name: "Mtro. Santiago Ríos"
    email: santiagoboo99@gmail.com
    affiliation: 
      - name: Cursos Orca
        city: CDMX
        url: orcaasesina.com
format: 
    live-html:
        highlightStyle: github
        highlightLines: true
        theme: superhero
toc: true
sidebar: false
webr:
    packages: 
        - tidyverse
        - ggpubr
        - datarium
        - emmeans
        - moments
    render-df: gt-interactive
engine: knitr
---


{{< include ../_extensions/r-wasm/live/_knitr.qmd >}}

Por último, vamos a ver cómo realizar un anova mixto en R. Este tipo de análisis combina factores entre sujetos y factores dentro de sujetos (como el tiempo).

Vamos a usar los datos `anxiety`del paquete `datarium` para realizar un ANOVA mixto. Estos datos contienen mediciones de ansiedad en diferentes momentos y bajo diferentes condiciones.

```{webr}
#| autorun: true
#| warning: false
library(tidyverse)
library(ggpubr)
library(rstatix)
library(datarium)

data("anxiety", package = "datarium")

# Convertir a formato largo
ansiedad <- anxiety %>%
  gather(key = "time", value = "score", t1, t2, t3) %>%
  convert_as_factor(id, time)

head(ansiedad)
```

Ahora vamos a realizar un ANOVA mixto para analizar la ansiedad en diferentes momentos y condiciones. Utilizaremos la función `anova_test` del paquete `rstatix` para realizar el análisis. Observa que ahora especificamos tanto el factor entre sujetos (`group`) como el factor dentro de sujetos (`time`).

```{webr}
#| autorun: true
#| warning: false

res.aov <- anova_test(
  data = ansiedad, 
  dv = score, 
  wid = id,
  between = group, 
  within = time
  )

get_anova_table(res.aov)
```


::: {.callout}
Con aov():

```{webr}
#| autorun: true
#| warning: false
aov(score ~ group * time + Error(id/time), data = ansiedad)
```

Con ezANOVA:

```{webr}
#| autorun: true
#| warning: false
library(ez)

ezANOVA(
  data = ansiedad,
  dv = score,
  wid = id,
  between = .(group),
  within = .(time),
  type = 2
)
```

:::

```{webr}
#| autorun: true
#| warning: false	
# Visualizar los resultados
bxp <- ggboxplot(
  ansiedad, x = "time", y = "score",
  color = "group", palette = "jco"
  )

# Comparaciones post-hoc
pwc <- ansiedad %>%
  group_by(time) %>%
  pairwise_t_test(score ~ group, p.adjust.method = "bonferroni")

# Visualizar las comparaciones post-hoc

pwc <- pwc %>% add_xy_position(x = "time")

# pwc.filtered <- pwc %>% filter(time != "t1")

bxp + 
  stat_pvalue_manual(pwc, tip.length = 0, hide.ns = TRUE) +
  labs(
    subtitle = get_test_label(res.aov, detailed = TRUE),
    caption = get_pwc_label(pwc)
  )
```

## Conclusiones

- En este tutorial, aprendiste a realizar un ANOVA mixto en R.
- El ANOVA mixto es útil para analizar datos con factores entre y dentro de sujetos.
- Puedes usar la función `anova_test` del paquete `rstatix` para realizar un ANOVA mixto.
- Si tienes diseños más complejos de los que vimos en este curso, intenta usar la función `ezANOVA` del paquete `ez` o la función `anova_test` del paquete `rstatix`. Lo más complicado es que tengas claro cuáles son tus factores entre y dentro de sujetos.