---
title: "Prueba de t para muestras pareadas"
author:
  - name: "Mtro. Santiago Ríos"
    email: santiagoboo99@gmail.com
    affiliation: 
      - name: Cursos Orca
        city: CDMX
        url: orcaasesina.com
format: 
    live-html:
        highlightStyle: github
        highlightLines: true
        theme: superhero
toc: true
sidebar: false
webr:
    packages: 
        - tidyverse
        - ggpubr
        - car
    render-df: gt-interactive
engine: knitr
---


{{< include ../_extensions/r-wasm/live/_knitr.qmd >}}


> **Muestra independiente**: Las muestras son independientes si las observaciones en un grupo no están relacionadas con las observaciones en el otro grupo. Por ejemplo, si se mide el peso de dos grupos (placebo vs tratamiento) de personas diferentes, los datos de un grupo no están relacionados con los datos del otro grupo.
> **Muestra pareada o emparejada**: Las muestras son pareadas si las observaciones en un grupo están relacionadas con las observaciones en el otro grupo. Por ejemplo, si se mide el peso de las mismas personas antes y después de un tratamiento, los datos de un grupo están relacionados con los datos del otro grupo.

## Datos de ejemplo

- Vamos a trabajar con datos simulados. En estos datos, tenemos una pareja de valores para una misma muestra. En este caso, representa el siguiente experimento:
  - 20 ratones reciben un tratamiento farmacológico durante 3 meses. Queremos saber si el tratamiento tiene un impacto en el peso de los ratones. El peso de los 20 ratones se mide antes y después del tratamiento. Como resultado, tenemos pares de valores de peso antes y después del tratamiento para cada ratón. Esto también se conoce como **muestra pareada** o **medidas repetidas**.  


```{webr}
#| autorun: true
#| warning: false

# Peso Antes del tratamiento
peso_antes <-c(200.1, 190.9, 192.7, 213, 241.4, 196.9, 172.2, 185.5, 205.2, 193.7)

# Peso Después del tratamiento
peso_despues <-c(392.9, 393.2, 345.1, 393, 434, 427.9, 422, 383.9, 392.3, 352.2)

# Crear dataframe
my_data <- data.frame( 
                grupo = rep(c("antes", "despues"), each = 10),
                peso = c(peso_antes,  peso_despues)
                )

my_data

```


## Hipótesis

- **Hipótesis nula (H0)**: La diferencia media entre los pesos antes y después del tratamiento es igual a 0.
- **Hipótesis alternativa (Ha)**: La diferencia media entre los pesos antes y después del tratamiento no es igual a 0.


## Resumen estadístico

```{webr}
#| autorun: true
#| warning: false

library("dplyr")

group_by(my_data, grupo) %>%
  summarise(
    n_cuenta = n(),
    media = mean(peso, na.rm = TRUE),
    sd = sd(peso, na.rm = TRUE)
  )

```

## Visualización preliminar de los datos

```{webr}
#| autorun: true
#| warning: false
library("ggpubr")

ggboxplot(my_data, x = "grupo", y = "peso", 
          color = "grupo", palette = c("#00AFBB", "#E7B800"),
          order = c("antes", "despues"),
          ylab = "Peso (g)", xlab = "Grupos")

```


## Comprobar supuestos

```{webr}
#| autorun: true
#| warning: false
library("dplyr")

# Diferencia entre los pesos antes y después del tratamiento
d <- my_data %>%
  filter(grupo == "antes") %>%
  pull(peso) - my_data %>%
  filter(grupo == "despues") %>%
  pull(peso)

# Shapiro-Wilk 
shapiro.test(d)

```

## Prueba de t para muestras pareadas

```{webr}
#| autorun: true
#| warning: false

# Compute t-test
res <- t.test(peso ~ grupos, data = my_data, paired = TRUE)
res

```