---
title: "Scripts en R"
author:
  - name: "Mtro. Santiago Ríos"
    email: santiagoboo99@gmail.com
    affiliation: 
      - name: Cursos Orca
        city: CDMX
        url: orcaasesina.com
format: 
    live-revealjs: 
        theme: serif
        toc: true
        scrollable: true
        progress: true
        slide-number: true
        incremental: true
        lang: es
        logo: "https://readr.tidyverse.org/logo.png"
        # code-link: true
# webr:
#     packages: 
#         - dplyr
engine: knitr
---

{{< include ../_extensions/r-wasm/live/_knitr.qmd >}}

## Scripts en R

- Un script en R es un archivo que contiene una serie de comandos que se ejecutan secuencialmente.
- Los scripts en R son útiles para automatizar tareas, reproducir análisis y compartir código con otros.
- Puedes ejecutar un script en RStudio seleccionando el código que deseas ejecutar y presionando `Ctrl + Enter`.
- También puedes ejecutar un script completo en RStudio presionando `Ctrl + Shift + S`.
- Los scripts en R tienen la extensión `.R`.
- Puedes crear un nuevo script en RStudio seleccionando `File > New File > R Script`.
- Para guardar un script en RStudio, selecciona `File > Save As` y elige la ubicación y el nombre del archivo.
- Para ejecutar un script en RStudio, selecciona `Source` en la pestaña superior del script.
- Los scripts en R pueden contener comentarios, que son líneas de texto que comienzan con el símbolo `#`.
- Los comentarios son útiles para documentar el código y explicar lo que hace cada parte del script.
- Los comentarios no se ejecutan y no afectan el resultado del script.
- Los scripts en R pueden contener funciones, que son bloques de código que realizan una tarea específica.

## Ejemplo de un Script en R

```{{r}}
# Este es un script en R que calcula la media de un vector de números

# Crear un vector de números
numeros <- c(1, 2, 3, 4, 5)

# Calcular la media de los números
media <- mean(numeros)

# Imprimir la media
print(media)

# Guardar la media en un archivo
write.csv(media, "media.csv")
```