---
title: "Primera lección con R"
subtitle: "Aprende a programar y estadística con R"
format:
  html:
    toc: true
    toc-depth: 2
---

Este cronograma está diseñado para dedicar al menos *30 minutos diarios* al estudio, proporcionando una estructura que facilita el aprendizaje progresivo.



Semana 1: Fundamentos de R

Día 1: Introducción a R y RStudio - Objetivo: Familiarizarse con el entorno de trabajo. - Contenido: - ¿Qué es R y por qué usarlo? - Instalación de R y RStudio. - Diapositivas: 8-10.

Día 2: Conceptos básicos de R - Objetivo: Comprender la sintaxis básica y tipos de datos. - Contenido: - Variables y asignación. - Tipos de datos básicos: numéricos, caracteres y lógicos. - Diapositivas: 8-10.

Día 3: Operadores y funciones básicas - Objetivo: Aprender a usar operadores matemáticos y lógicos. - Contenido: - Operaciones aritméticas y lógicas. - Funciones básicas: sum(), mean(), etc. - Diapositivas: 8-10.

Día 4: Estructuras de datos en R - Objetivo: Familiarizarse con vectores, listas y data frames. - Contenido: - Creación y manipulación de vectores y listas. - Introducción a data frames. - Diapositivas: 10-12.

Día 5: Importación y exportación de datos - Objetivo: Aprender a importar/exportar datos desde/a varios formatos. - Contenido: - Lectura de archivos CSV, Excel. - Escritura de datos en archivos. - Diapositivas: 8-10.

Día 6: Manipulación de datos con dplyr - Objetivo: Introducir la manipulación de datos eficiente. - Contenido: - Uso de select(), filter(), mutate(), summarize(). - Diapositivas: 10-12.

Día 7: Repaso y ejercicios prácticos - Objetivo: Reforzar los conceptos aprendidos con ejercicios prácticos. - Contenido: - Ejercicios interactivos y revisión. - Diapositivas: Usa material previamente discutido.
Semana 2: Introducción a la Bioestadística



## Conceptos básicos de R

### Paquetes

{{< revealjs file="../slides/02-paquetes-r.html" height="500px">}}

## Datos

- https://datasciencebox.org/course-materials/_slides/u2-d01-data-viz/u2-d01-data-viz#1

### Tipos de datos

https://datasciencebox.org/course-materials/_slides/u2-d03-viz-num/u2-d03-viz-num#1

{{< revealjs file="../slides/02-datos-intro.html" height="500px">}}

https://github.com/nlarrea/R-desde-cero/blob/main/TEORIA/03-estructuras-de-datos/README.md#estructuras-de-datos

### Importar datos

{{< revealjs file="../slides/02-datos-importar.html" height="500px">}}

https://datasciencebox.org/course-materials/_slides/u2-d12-data-import/u2-d12-data-import#1

https://github.com/nlarrea/R-desde-cero/blob/main/TEORIA/04-importar-exportar-datos/README.md#importar-y-exportar-datos



## Introducción a la programación

{{< revealjs file="../slides/01-karel.html" height="500px">}}

{{< revealjs file="../slides/02-programacion-intro.html" height="500px">}}

https://stanford.edu/~cpiech/karel/lessons.html#/english/unit2/lesson3
https://cran.r-project.org/web/packages/karel/vignettes/b_meetingkarel_es.html
https://ropensci.github.io/karel/
https://homerhanumat.github.io/r-notes/turtle.html
https://p4a.seas.gwu.edu/2019-Fall/TurtleGraphics.html

https://github.com/nlarrea/R-desde-cero/blob/main/TEORIA/02-control-de-flujo/README.md#condiciones-bucles-y-funciones

### Funciones e introducción a tidyverse

https://datasciencebox.org/course-materials/_slides/u2-d05-tidy-data/u2-d05-tidy-data#1

https://datasciencebox.org/course-materials/_slides/u2-d06-grammar-wrangle/u2-d06-grammar-wrangle#1

{{< revealjs file="../slides/02-funciones-r.html" height="500px">}}

https://datasciencebox.org/course-materials/_slides/u2-d07-single-df/u2-d07-single-df#1

https://datasciencebox.org/course-materials/_slides/u2-d08-multi-df/u2-d08-multi-df#1

https://datasciencebox.org/course-materials/_slides/u2-d09-tidying/u2-d09-tidying#1

### Funciones básicas en estadística

https://github.com/nlarrea/R-desde-cero/blob/main/TEORIA/05-analizar-datos/README.md#analizar-datos

{{< revealjs file="../slides/02-funciones-estadistica.html" height="500px">}}

https://datasciencebox.org/course-materials/_slides/u2-d10-data-types/u2-d10-data-types#1

https://datasciencebox.org/course-materials/_slides/u2-d11-data-classes/u2-d11-data-classes#3

https://datasciencebox.org/course-materials/_slides/u2-d13-data-recode/u2-d13-data-recode#1

https://minecr.shinyapps.io/dsbox-02-accidents/

https://minecr.shinyapps.io/dsbox-03-collegemajors/

### Funciones básicas para Visualización

https://github.com/nlarrea/R-desde-cero/blob/main/TEORIA/06-graficos/README.md#gr%C3%A1ficos

{{< revealjs file="../slides/02-funciones-visualizacion.html" height="500px">}}

## Errores comunes

{{< revealjs file="../slides/02-errores-comunes.html" height="500px">}}

## Programación en R

{{< revealjs file="../slides/02-programacion-ll.html" height="500px">}}

## scripts

{{< revealjs file="../slides/02-scripts-r.html" height="500px">}}

## Ejercicios

https://minecr.shinyapps.io/dsbox-01-edibnb/#section-data-visualisation