---
title: "Modelos Estadísticos y Análisis"
format:
  html:
    toc: true
    toc-depth: 2
---

statistics with r
https://r-coder.com/r-statistics/

rcharts
https://r-coder.com/r-graphs/ 

data manipulation
https://r-coder.com/r-data-manipulation/

Este módulo serviría para ampliar las capacidades de los estudiantes en la aplicación de técnicas más sofisticadas en estadística, lo cual es esencial para un análisis más riguroso y profundo de los datos. Aquí tienes algunas sugerencias de temas y subtemas para este módulo:
Módulo 3: Modelos Estadísticos y Análisis Avanzados

    Regresión Lineal Múltiple:
        Extensión de la regresión lineal simple a múltiples variables independientes.
        Interpretación de coeficientes y uso de R para ajustar modelos de regresión múltiple.

    Análisis de Varianza (ANOVA):
        Conceptos básicos de ANOVA para comparar más de dos grupos.
        ANOVA de un factor y ANOVA de medidas repetidas en R.

    Regresión Logística:
        Modelado de variables dependientes categóricas binarias.
        Interpretación de odds ratios y ajuste de modelos de regresión logística en R.

    Series de Tiempo:
        Introducción al análisis de datos de series de tiempo.
        Técnicas básicas de suavizamiento y modelado de series de tiempo en R (como el método de Holt-Winters).

    Análisis de Clúster:
        Métodos de agrupamiento como k-means y jerárquicos.
        Aplicaciones prácticas y visualización de clústeres en R.

    Análisis de Componentes Principales (PCA):
        Reducción de dimensionalidad y visualización de patrones complejos.
        Realización de un PCA en R y entendimiento de los componentes principales.

    Modelos de Supervivencia:
        Conceptos básicos de análisis de supervivencia y la función de riesgo.
        Aplicación de modelos de supervivencia en R, como modelos de Cox.

    Análisis Bayesiano:
        Introducción a conceptos bayesianos.
        Uso de paquetes de R para realizar inferencias bayesianas básicas.

Este módulo proporcionaría una comprensión más profunda y técnica de cómo aplicar modelos estadísticos y análisis avanzados en datos reales, fortaleciendo aún más las habilidades de los estudiantes en análisis de datos y estadística con R.


{{< revealjs file="../slides/01-r-comparacionotros.html" height="500px">}}


## Variables

{{< revealjs file="../slides/03-variables-intro.html" height="500px">}}

## Distribuciones de Probabilidad



### i - Distribuciones

{{< revealjs file="../slides/03-distribuciones-probabilidad.html" height="500px">}}

{{< revealjs file="../slides/03-histogramas-ggplot.html" height="500px">}}

{{< revealjs file="../slides/03-distribuciones-nonom.html" height="500px">}}

{{< revealjs file="../slides/03-teorema-limite.html" height="500px">}}

{{< revealjs file="../slides/03-visualizacion-datosll.html" height="500px">}}

{{< revealjs file="../slides/03-visualizacion-datos.html" height="500px">}}

{{< revealjs file="../slides/03-visualizacion-datosIII.html" height="500px">}}

### Evaluación introducción R y Estadística

{{< revealjs file="../slides/04-ejercicios-evalintro.html" height="500px">}}

{{< revealjs file="../slides/04-ejercicios-evalintroII.html" height="500px">}}



## Ejercicios

https://minecr.shinyapps.io/dsbox-04-legosales/#section-counting-frequencies

https://minecr.shinyapps.io/dsbox-06-dcbikeshare/

https://minecr.shinyapps.io/dsbox-07-exploregss/

