---
title: "Estadística Aplicada y Tópicos Avanzados"
format:
  html:
    toc: true
    toc-depth: 2
---

Módulo 4: Estadística Aplicada y Tópicos Avanzados

https://datasciencebox.org/02-looking-further

## Bioestadística y Estadística Genómica:

Análisis estadístico en datos genómicos y de proteómica.
Uso de herramientas como Bioconductor para el análisis de datos biológicos.

## Modelos Mixtos:

Introducción a modelos de efectos aleatorios y fijos.
Aplicación de modelos lineales generalizados mixtos (GLMMs) en R.


## Estadística Multivariada Avanzada:

Análisis de correspondencias múltiples.
Regresión parcial menos cuadrados (PLS).
Análisis discriminante lineal y cuadrático.

## Minería de Datos y Machine Learning:

Introducción a técnicas de machine learning con R.
Algoritmos supervisados como árboles de decisión, random forests y support vector machines (SVM).
Algoritmos no supervisados como clustering y reducción de dimensionalidad.

## Análisis de Redes Sociales:

Conceptos básicos de redes y grafos.
Análisis de redes sociales con R utilizando bibliotecas como igraph.

## Estadística Espacial:

Análisis estadístico de datos espaciales.
Modelos de puntos y geoestadística aplicada.

## Evaluación de Políticas Públicas:

Métodos estadísticos para la evaluación de impacto.
Análisis de intención de tratar y métodos de regresión discontinua.

## Análisis de Datos de Encuestas:

Diseño y análisis de encuestas.
Uso de R para analizar datos de sondeos y encuestas complejas.

## Simulación Estadística:

Técnicas de simulación para pruebas de hipótesis y generación de datos.
Uso de simulación de Monte Carlo para análisis estadístico.

## apps

https://www.shinyapps.org/apps/p-hacker/

https://www.shinyapps.org/showapp.php?app=https://shiny.psy.lmu.de/felix/z-to-p/&by=Sven%20Hilbert&title=From%20z%20to%20p:%20A%20visualization%20of%20the%20link%20between%20the%20two%20distributions&shorttitle=From%20z%20to%20p

https://www.shinyapps.org/showapp.php?app=https://shiny.psy.lmu.de/felix/lakens_pcurve/&by=Daniel%20Lakens&title=P-value%20distribution%20and%20power%20curves%20for%20an%20independent%20two-tailed%20t-test&shorttitle=P-value%20distribution%20and%20power%20curves

https://www.shinyapps.org/apps/RGraphCompendium/index.php

https://www.shinyapps.org/showapp.php?app=https://shiny.psy.lmu.de/felix/lmfit&by=Felix%20Sch%C3%B6nbrodt&title=Find-a-fit!&shorttitle=Find-a-fit!

https://www.shinyapps.org/showapp.php?app=https://shiny.psy.lmu.de/felix/TK/1&by=Tobias%20K%C3%A4chele&title=Robustness%20of%20Mean%20and%20Median&shorttitle=Robustness%20of%20Mean%20and%20Median

https://www.shinyapps.org/showapp.php?app=https://shiny.psy.lmu.de/felix/TK/2&by=Tobias%20K%C3%A4chele&title=Normal%20distribution%20vs.%20binomial&shorttitle=Normal%20distribution%20vs.%20binomial

https://www.shinyapps.org/showapp.php?app=https://shiny.psy.lmu.de/felix/TK/3&by=Tobias%20K%C3%A4chele&title=Production%20errors&shorttitle=Production%20errors

boxplot
https://gallery.shinyapps.io/boxplot/

https://shiny.srvanderplas.com/r-graph-catalog/

https://gallery.shinyapps.io/correlation_game/

https://shiny.posit.co/r/gallery/start-simple/single-file-shiny-app/

https://gallery.shinyapps.io/tdist/

https://gallery.shinyapps.io/dist_calc/

https://gallery.shinyapps.io/sampling_and_stderr/

https://gallery.shinyapps.io/sampling_and_stderr/

https://gallery.shinyapps.io/CLT_mean/

https://gallery.shinyapps.io/anova_shiny_rstudio/

https://gallery.shinyapps.io/simple_regression/

https://paternogbc.shinyapps.io/SS_regression/

http://shinyapps.org/showapp.php?app=http://lmpp10e-mucesm.srv.mwn.de:3838/felix/lmfit&by=Felix%20Sch%C3%B6nbrodt&title=Find-a-fit!&shorttitle=Find-a-fit!

https://gallery.shinyapps.io/slr_diag/

https://omaymas.shinyapps.io/Influence_Analysis/

https://gallery.shinyapps.io/collinearity/

https://gallery.shinyapps.io/multi_regression/

http://kylehamilton.net/shiny/MAVIS/

http://www.intro-stats.com/

https://sites.google.com/view/ben-prytherch-shiny-apps/shiny-apps

https://csu-statistics.shinyapps.io/ANOVA_factorial_data_generator/

https://csu-statistics.shinyapps.io/Mixed_effects_ANOVA_data_generator/

https://csu-statistics.shinyapps.io/Random_slopes_data_generator/

https://csu-statistics.shinyapps.io/Tukey_vs_t/

https://csu-statistics.shinyapps.io/Tukey_vs_t/

https://csu-statistics.shinyapps.io/ANOVA_oneway_generative/

https://www.google.com/url?q=https%3A%2F%2Fcsu-statistics.shinyapps.io%2FANCOVA_data_generator%2F&sa=D&sntz=1&usg=AOvVaw0s3B8xu6TlhJ5CQDezp2zX

https://csu-statistics.shinyapps.io/ANCOVA_data_generator/

https://csu-statistics.shinyapps.io/ANCOVA_data_generator/

https://csu-statistics.shinyapps.io/ANOVA_oneway_generative/

https://csu-statistics.shinyapps.io/logistic_regression_data_generator/

https://csu-statistics.shinyapps.io/stats_from_repeated_samples/

https://statistics.calpoly.edu/shiny

http://shiny.calpoly.sh/Corr_Reg_Game/
https://calpolystat1.shinyapps.io/corr_reg_game/

http://shiny.calpoly.sh/WilcoxonMW/
https://calpolystat3.shinyapps.io/WilcoxonMW/

http://shiny.calpoly.sh/t_Test/
https://calpolystat3.shinyapps.io/t_test/

http://shiny.calpoly.sh/ANOVA_robust/
https://calpolystat1.shinyapps.io/ANOVA_robust/

http://shiny.calpoly.sh/Prob_View/
https://calpolystat1.shinyapps.io/prob_view/

http://shiny.calpoly.sh/RandVarGen/
https://calpolystat2.shinyapps.io/RandVarGen/

http://shiny.calpoly.sh/Sampling_Distribution/
https://calpolystat1.shinyapps.io/sampling_distribution/

http://shiny.calpoly.sh/Hierarchical_Models/
https://calpolystat3.shinyapps.io/Hierarchical_Models/

http://shiny.calpoly.sh/SP_Render/

