---
title: "ANOVA de medidas repetidas"
subtitle: "Valores atípicos, normalidad y homogeneidad de varianzas"
author:
  - name: "Mtro. Santiago Ríos"
    email: santiagoboo99@gmail.com
    affiliation: 
      - name: Cursos Orca
        city: CDMX
        url: orcaasesina.com
format: 
    live-html:
        highlightStyle: github
        highlightLines: true
        theme: superhero
toc: true
sidebar: false
webr:
    packages: 
        - tidyverse
        - ggpubr
        - datarium
        - emmeans
        - moments
    render-df: gt-interactive
engine: knitr
---


{{< include ../_extensions/r-wasm/live/_knitr.qmd >}}


El ANOVA de medidas repetidas se utiliza para analizar datos donde los mismos sujetos se miden más de una vez. Esta prueba también se conoce como ANOVA intra-sujetos o ANOVA con medidas repetidas. El término "intra-sujetos" significa que los mismos individuos son medidos en la misma variable de resultado bajo diferentes puntos de tiempo o condiciones. Por ejemplo, podrías haber medido la puntuación de autoestima (la variable de resultado o dependiente) de 10 individuos en tres momentos durante una dieta específica para determinar si su autoestima mejoró.

Existen diferentes tipos de ANOVA de medidas repetidas, incluyendo:

- ANOVA de medidas repetidas de una vía, una extensión de la prueba t de muestras pareadas para comparar las medias de tres o más niveles de una variable intra-sujetos.
- ANOVA de medidas repetidas de dos vías, utilizado para evaluar simultáneamente el efecto de dos factores intra-sujetos sobre una variable de resultado continua.

::: {.callout-important}
Recuerda revisar los valores atípicos y la normalidad antes de realizar un ANOVA de medidas repetidas.
:::


```{webr}
#| autorun: true
#| warning: false
library(tidyverse)
library(ggpubr)
library(rstatix)
library(datarium)
```

## ANOVA de una vía

### Datos

- vamos a usar datos de autoestima medido en tres momentos diferentes:

```{webr}
#| autorun: true
#| warning: false
data("selfesteem", package = "datarium")
head(selfesteem, 3)
```

- `id`: identificador del sujeto
- `t_`: tiempo de medición

Vamos a ordenar los datos para que las 3 columnas de tiempo estén juntas en una sola columna:

```{webr}
#| autorun: true
#| warning: false
selfesteem_long <- selfesteem %>% 
  pivot_longer(cols = starts_with("t"), names_to = "tiempo", values_to = "autoestima")

selfesteem_long

```

### ANOVA

- Vamos a realizar el ANOVA con la función `anova_test()` de `rstatix`.
- Observa que estamos especificando el `id` del sujeto y la variable `tiempo` como factores intra-sujetos. Esto es importante para que el análisis sea correcto y considere que es un diseño de medidas repetidas. Al final, se usa `get_anova_table()` para obtener la tabla ANOVA.

```{webr}
#| autorun: true
#| warning: false

res.aov <- anova_test(data = selfesteem_long, dv = autoestima, wid = id, within = tiempo)

get_anova_table(res.aov)

```

::: {.callout-note}

Si quisiéramos realizar este mismo ANOVA con la función `aov()` de R, tendríamos que especificar el diseño de medidas repetidas con la función `Error()`. Esto puede ser un poco más complicado que con `anova_test()`.

```{webr}
#| autorun: true
#| warning: false
res.aov.2 <- aov(autoestima ~ tiempo + Error(id/tiempo), data = selfesteem_long)

summary(res.aov.2)
```

También se puede realizar con la función `ezANOVA()` del paquete `ez`:

```{webr}
#| autorun: true
#| warning: false
library(ez)


# EZ ANOVA approach
res.ez <- ezANOVA(
  data = selfesteem_long,
  dv = autoestima,
  wid = id,
  within = tiempo,
  type = 2
)


print(res.ez)
```

:::

### gráfico y post-hoc

- Vamos a hacer el gráfico con los valores del ANOVA y los resultados del post-hoc:

```{webr}
#| autorun: true
#| warning: false
pwc <- selfesteem_long %>%
  pairwise_t_test(
    autoestima ~ tiempo, paired = TRUE,
    p.adjust.method = "bonferroni"
    )

pwc <- pwc %>% add_xy_position(x = "tiempo")

bxp <- ggboxplot(selfesteem_long, x = "tiempo", y = "autoestima", add = "point")

bxp + 
  stat_pvalue_manual(pwc) +
  labs(
    subtitle = get_test_label(res.aov, detailed = TRUE),
    caption = get_pwc_label(pwc)
  )

```


## ANOVA de dos vías

### Datos

Ahora usaremos los datos `selfesteem2` que contienen autoestima de 12 individuos en 2 tiempos bajo 2 condiciones diferentes: control y tratamiento.


```{webr}
#| autorun: true
#| warning: false	
set.seed(123)
data("selfesteem2", package = "datarium")
selfesteem2 %>% sample_n_by(treatment, size = 1)
```

> Limpiar datos:

```{webr}
#| autorun: true
#| warning: false

selfesteem2_long <- selfesteem2 %>%
  gather(key = "time", value = "score", t1, t2, t3) %>%
  convert_as_factor(id, time)

head(selfesteem2_long)
```


### ANOVA


```{webr}
#| autorun: true
#| warning: false
res.aov.3 <- anova_test(
  data = selfesteem2_long, dv = score, wid = id,
  within = c(treatment, time)
  )

get_anova_table(res.aov.3)
```

::: {.callout}
- con `aov`:

```{webr}
#| autorun: true
#| warning: false
aov(score ~ treatment * time + Error(id/(treatment*time)), data = selfesteem2_long)
```

- Con `ez`:

```{webr}
#| autorun: true
#| warning: false

ezANOVA(
  data = selfesteem2_long,
  dv = score,
  wid = id,
  within = .(treatment, time),
  type = 2
)


```

:::

```{webr}
#| autorun: true
#| warning: false
bxp.2 <- ggboxplot(
  selfesteem2_long, x = "time", y = "score",
  color = "treatment", palette = "jco"
  )


pwc.2 <- selfesteem2_long %>%
  group_by(time) %>%
  pairwise_t_test(
    score ~ treatment, paired = TRUE,
    p.adjust.method = "bonferroni"
    )

pwc.2 <- pwc.2 %>% add_xy_position(x = "time")

bxp.2 + 
  stat_pvalue_manual(pwc.2, tip.length = 0, hide.ns = TRUE) +
  labs(
    subtitle = get_test_label(res.aov.3, detailed = TRUE),
    caption = get_pwc_label(pwc.2)
  )
```
