---
title: "Comparar media de dos grupos independientes con t-test en R"
author:
  - name: "Mtro. Santiago Ríos"
    email: santiagoboo99@gmail.com
    affiliation: 
      - name: Cursos Orca
        city: CDMX
        url: orcaasesina.com
format: 
    live-html:
        highlightStyle: github
        highlightLines: true
        theme: superhero
toc: true
sidebar: false
webr:
    packages: 
        - tidyverse
        - ggpubr
        - car
    render-df: gt-interactive
engine: knitr
---


{{< include ../_extensions/r-wasm/live/_knitr.qmd >}}


> **Muestra independiente**: Las muestras son independientes si las observaciones en un grupo no están relacionadas con las observaciones en el otro grupo. Por ejemplo, si se mide el peso de dos grupos (placebo vs tratamiento) de personas diferentes, los datos de un grupo no están relacionados con los datos del otro grupo.
> **Muestra pareada o emparejada**: Las muestras son pareadas si las observaciones en un grupo están relacionadas con las observaciones en el otro grupo. Por ejemplo, si se mide el peso de las mismas personas antes y después de un tratamiento, los datos de un grupo están relacionados con los datos del otro grupo.

## Ejemplo Práctico

- Vamos a trabajar con datos simulados. En estos datos, tenemos las medidas de peso de dos grupos de personas: 50 mujeres (grupo A) y 50 hombres (grupo B). Queremos saber si la media de peso de las mujeres (A) es significativamente diferente de la de los hombres (B).
- En este caso, tenemos dos grupos de muestras no relacionadas (es decir, independientes o no pareadas). Por lo tanto, es posible utilizar una prueba t independiente para evaluar si las medias son diferentes.

```{webr}
#| autorun: true
#| warning: false

# Datos Simulados
A_mujeres <- c(38.9, 61.2, 73.3, 21.8, 63.4, 64.6, 48.4, 48.8, 48.5)

B_hombres <- c(67.8, 60, 63.4, 76, 89.4, 73.3, 67.3, 61.3, 62.4) 

my_data <- data.frame( 
                grupo = rep(c("Mujer", "Hombre"), each = 9),
                pesos = c(A_mujeres,  B_hombres)
                )

my_data
```

::: {.callout-note}
## Condiciones para usar la prueba t de dos muestras no pareadas

- Las dos muestras (A y B) deben ser independientes. Esto lo comprobamos al recolectar los datos (sabemos que el grupo de mujeres no está relacionado con el grupo de hombres).
- Las dos muestras (A y B) deben ser aproximadamente distribuidas normalmente. Esto se puede verificar utilizando la prueba de Shapiro-Wilk.
- Las dos muestras (A y B) deben tener varianzas iguales. Esto se puede verificar utilizando la prueba F.

:::

## Hipótesis de investigación

- $H_0$: La media de peso de las mujeres (A) es igual a la media de peso de los hombres (B).
- $H_1$: La media de peso de las mujeres (A) es diferente de la media de peso de los hombres (B).


## Visualización preliminar de los datos

**Gráfico de caja**

```{webr}
#| autorun: true
#| warning: false

library("ggpubr")

ggboxplot(my_data, x = "grupo", y = "pesos", 
          color = "grupo", palette = c("#00AFBB", "#E7B800"),
        ylab = "Peso", xlab = "Grupos")

```

**Estadísticas descriptivas**

```{webr}
#| autorun: true
#| warning: false

library(dplyr)

group_by(my_data, grupo) %>%
  summarise(
    cuenta_n = n(), # Número de observaciones
    media = mean(pesos, na.rm = TRUE), # Media
    sd = sd(pesos, na.rm = TRUE) # Desviación estándar
  )
```

## Prueba de normalidad

**Prueba de Shapiro-Wilk**

- Hipótesis nula: los datos siguen una distribución normal.
- Hipótesis alternativa: los datos no siguen una distribución normal.

```{webr}
#| autorun: true
#| warning: false

library(dplyr)

# Prueba de normalidad para el grupo de mujeres
my_data %>%
    filter(grupo == "Mujer") %>%
    summarise(p_value = shapiro.test(pesos)$p.value)

# Prueba de normalidad para el grupo de hombres
my_data %>%
    filter(grupo == "Hombre") %>%
    summarise(p_value = shapiro.test(pesos)$p.value)
```

::: {.callout}
En ambos casos, el *p-value* es mayor que el nivel de significancia `0.05`, lo que indica que los datos no son significativamente diferentes de una distribución normal.
:::


## Prueba de homogeneidad de varianzas

- Podemos usar la prueba F para probar la homogeneidad de varianzas con la función `var.test()`.
- $H_0$: Las varianzas de los dos grupos son iguales.
- $H_1$: Las varianzas de los dos grupos son diferentes.

```{webr}
#| autorun: true
#| warning: false

res.ftest <- var.test(pesos ~ grupo, data = my_data)
res.ftest
```

::: {.callout}

- No hay evidencia significativa para rechazar la hipótesis nula de igualdad de varianzas.
- Por lo tanto, podemos usar la prueba t clásica que asume igualdad de varianzas.
- En caso que las varianzas no fueran iguales, se recomienda usar la prueba t de Welch. Para esto, solo necesitas cambiar el argumento `var.equal = FALSE` en la función `t.test()`.

:::

## Prueba de t de Student

```{webr}	
#| autorun: true
#| warning: false

res <- t.test(pesos ~ grupo, data = my_data, var.equal = TRUE)

res

```

::: {.callout}

- El valor p de la prueba es `0.01327`, que es menor que el nivel de significancia `alpha = 0.05`.
- Por lo tanto, podemos concluir que la media de peso de los hombres es significativamente diferente de la de las mujeres con un valor p = `0.01327`.

:::



```{webr}	
#| autorun: true
#| warning: false

res$p.value # p-value
```


```{webr}	
#| autorun: true
#| warning: false

res$estimate # media

```

```{webr}	
#| autorun: true
#| warning: false


res$conf.int # intervalo de confianza
```


## Gráfico para visualizar la diferencia de medias y la prueba estadística


::: {.callout}

Podemos visualizar la diferencia de medias y la prueba estadística en un gráfico de caja. 

OJO. El gráfico de `ggpubr` redondea el valor de la prueba de t a 3 decimales, mientras que la función `t.test()` devuelve un valor más preciso.
:::

```{webr}
#| autorun: true
#| warning: false

library("ggpubr")

p <- ggboxplot(my_data, x = "grupo", y = "pesos", 
          color = "grupo", palette = c("#00AFBB", "#E7B800"),
        ylab = "Peso", xlab = "Grupos",
               add = "jitter")

p + stat_compare_means(method = "t.test", paired = FALSE)

```

::: {.callout}
## Opción 2 - Con gráficos de barras y Error Estándar de la Media

```{webr}
#| autorun: true
#| warning: false

library("ggpubr")

p <- ggbarplot(my_data, x = "grupo", y = "pesos", 
          fill = "grupo", palette = c("#00AFBB", "#E7B800"),
        ylab = "Peso", xlab = "Grupos",
               add = c("mean_se", "jitter")
                      )

p + stat_compare_means(method = "t.test", paired = FALSE)

```

:::